print("Hello, I am the Python Calculator. I can be used to calculate in the basic operations up to ten numbers. All answers are either floating point numbers(ex. 3.7, 5.1,...) or integers. Please type (case sensitive) add(ex. x+y+z+.....), subtract(ex. x-y-z-a-b.....), multiply(ex. x*y*z*....), divide(ex. w/x/y/z/...), or quit to exit program. When I ask for numbers, please write digits and NOT THE WORD FOR THE NUMBER.")
print("Please write what operation you would like for me to calculate.")
operation = str(input("--> "))
if operation == "add":
   print("How many numbers do you want to add together? Number from 2-10")
   num_digits = int(input("--> "))
   print("Are you trying to add decimals? Write 'decimal' or 'integer'. 'decimal' will give you a floating point number(ex. 3.5, 7.8,...). 'integer' will give you an integer.")
   num_type = str(input("-->"))
   if num_type == "decimal":
      if num_digits == 2: 
         print("What is your first number to add?")
         first_num = float(input("--> "))
         print("What is your second number to add?")
         second_num = float(input("--> "))
         ans = float(first_num + second_num)
         print("The result is ", ans, ".")
      elif num_digits == 3:
         print("What is your first number to add?")
         first_num = float(input("--> "))
         print("What is your second number to add?")
         second_num = float(input("--> "))
         print("What is your third number to add?")
         third_num = float(input("--> "))
         ans = float(first_num + second_num + third_num)
         print("The result is ", ans, ".")
      elif num_digits == 4:
         print("What is your first number to add?")
         first_num = float(input("--> "))
         print("What is your second number to add?")
         second_num = float(input("--> "))
         print("What is your third number to add?")
         third_num = float(input("--> "))
         print("What is your fourth number to add?")
         fourth_num = float(input("--> "))
         ans = float(first_num + second_num + third_num + fourth_num)
         print("The result is ", ans, ".")
      elif num_digits == 5:
         print("What is your first number to add?")
         first_num = float(input("--> "))
         print("What is your second number to add?")
         second_num = float(input("--> "))
         print("What is your third number to add?")
         third_num = float(input("--> "))
         print("What is your fourth number to add?")
         fourth_num = float(input("--> "))
         print("What is your fifth number to add?")
         fifth_num = float(input("--> "))
         ans = float(first_num + second_num + third_num + fourth_num + fifth_num)
         print("The result is ", ans, ".")
      elif num_digits == 6:
         print("What is your first number to add?")
         first_num = float(input("--> "))
         print("What is your second number to add?")
         second_num = float(input("--> "))
         print("What is your third number to add?")
         third_num = float(input("--> "))
         print("What is your fourth number to add?")
         fourth_num = float(input("--> "))
         print("What is your fifth number to add?")
         fifth_num = float(input("--> "))
         print("What is your sixth number to add?")
         sixth_num = float(input("--> "))
         ans = float(first_num + second_num + third_num + fourth_num + fifth_num + sixth_num)
         print("The result is ", ans, ".")
      elif num_digits == 7:
         print("What is your first number to add?")
         first_num = float(input("--> "))
         print("What is your second number to add?")
         second_num = float(input("--> "))
         print("What is your third number to add?")
         third_num = float(input("--> "))
         print("What is your fourth number to add?")
         fourth_num = float(input("--> "))
         print("What is your fifth number to add?")
         fifth_num = float(input("--> "))
         print("What is your sixth number to add?")
         sixth_num = float(input("--> "))
         print("What is your seventh number to add?")
         seventh_num = float(input("--> "))
         ans = float(first_num + second_num + third_num + fourth_num + fifth_num + sixth_num + seventh_num)
         print("The result is ", ans, ".")
      elif num_digits == 8:
         print("What is your first number to add?")
         first_num = float(input("--> "))
         print("What is your second number to add?")
         second_num = float(input("--> "))
         print("What is your third number to add?")
         third_num = float(input("--> "))
         print("What is your fourth number to add?")
         fourth_num = float(input("--> "))
         print("What is your fifth number to add?")
         fifth_num = float(input("--> "))
         print("What is your sixth number to add?")
         sixth_num = float(input("--> "))
         print("What is your seventh number to add?")
         seventh_num = float(input("--> "))
         print("What is your eighth number to add?")
         eighth_num = float(input("--> "))
         ans = float(first_num + second_num + third_num + fourth_num + fifth_num + sixth_num + seventh_num + eighth_num)
         print("The result is ", ans, ".")
      elif num_digits == 9:
         print("What is your first number to add?")
         first_num = float(input("--> "))
         print("What is your second number to add?")
         second_num = float(input("--> "))
         print("What is your third number to add?")
         third_num = float(input("--> "))
         print("What is your fourth number to add?")
         fourth_num = float(input("--> "))
         print("What is your fifth number to add?")
         fifth_num = float(input("--> "))
         print("What is your sixth number to add?")
         sixth_num = float(input("--> "))
         print("What is your seventh number to add?")
         seventh_num = float(input("--> "))
         print("What is your eighth number to add?")
         eighth_num = float(input("--> "))
         print("What is your ninth number to add?")
         ninth_num = float(input("--> "))
         ans = float(first_num + second_num + third_num + fourth_num + fifth_num + sixth_num + seventh_num + eighth_num + ninth_num)
         print("The result is ", ans, ".")
      elif num_digits == 10:
         print("What is your first number to add?")
         first_num = float(input("--> "))
         print("What is your second number to add?")
         second_num = float(input("--> "))
         print("What is your third number to add?")
         third_num = float(input("--> "))
         print("What is your fourth number to add?")
         fourth_num = float(input("--> "))
         print("What is your fifth number to add?")
         fifth_num = float(input("--> "))
         print("What is your sixth number to add?")
         sixth_num = float(input("--> "))
         print("What is your seventh number to add?")
         seventh_num = float(input("--> "))
         print("What is your eighth number to add?")
         eighth_num = float(input("--> "))
         print("What is your ninth number to add?")
         ninth_num = float(input("--> "))
         print("What is your tenth number to add?")
         tenth_num = float(input("--> "))
         ans = float(first_num + second_num + third_num + fourth_num + fifth_num + sixth_num + seventh_num + eighth_num + ninth_num + tenth_num)
         print("The result is ", ans, ".")
      else:
         print("Please check your syntax. Rerun program and try again.")
   elif num_type == "integer":
      if num_digits == 2: 
         print("What is your first number to add?")
         first_num = int(input("--> "))
         print("What is your second number to add?")
         second_num = int(input("--> "))
         ans = int(first_num + second_num)
         print("The result is ", ans, ".")
      elif num_digits == 3:
         print("What is your first number to add?")
         first_num = int(input("--> "))
         print("What is your second number to add?")
         second_num = int(input("--> "))
         print("What is your third number to add?")
         third_num = int(input("--> "))
         ans = int(first_num + second_num + third_num)
         print("The result is ", ans, ".")
      elif num_digits == 4:
         print("What is your first number to add?")
         first_num = int(input("--> "))
         print("What is your second number to add?")
         second_num = int(input("--> "))
         print("What is your third number to add?")
         third_num = int(input("--> "))
         print("What is your fourth number to add?")
         fourth_num = int(input("--> "))
         ans = int(first_num + second_num + third_num + fourth_num)
         print("The result is ", ans, ".")
      elif num_digits == 5:
         print("What is your first number to add?")
         first_num = int(input("--> "))
         print("What is your second number to add?")
         second_num = int(input("--> "))
         print("What is your third number to add?")
         third_num = int(input("--> "))
         print("What is your fourth number to add?")
         fourth_num = int(input("--> "))
         print("What is your fifth number to add?")
         fifth_num = int(input("--> "))
         ans = int(first_num + second_num + third_num + fourth_num + fifth_num)
         print("The result is ", ans, ".")
      elif num_digits == 6:
         print("What is your first number to add?")
         first_num = int(input("--> "))
         print("What is your second number to add?")
         second_num = int(input("--> "))
         print("What is your third number to add?")
         third_num = int(input("--> "))
         print("What is your fourth number to add?")
         fourth_num = int(input("--> "))
         print("What is your fifth number to add?")
         fifth_num = int(input("--> "))
         print("What is your sixth number to add?")
         sixth_num = int(input("--> "))
         ans = int(first_num + second_num + third_num + fourth_num + fifth_num + sixth_num)
         print("The result is ", ans, ".")
      elif num_digits == 7:
         print("What is your first number to add?")
         first_num = int(input("--> "))
         print("What is your second number to add?")
         second_num = int(input("--> "))
         print("What is your third number to add?")
         third_num = int(input("--> "))
         print("What is your fourth number to add?")
         fourth_num = int(input("--> "))
         print("What is your fifth number to add?")
         fifth_num = int(input("--> "))
         print("What is your sixth number to add?")
         sixth_num = int(input("--> "))
         print("What is your seventh number to add?")
         seventh_num = int(input("--> "))
         ans = int(first_num + second_num + third_num + fourth_num + fifth_num + sixth_num + seventh_num)
         print("The result is ", ans, ".")
      elif num_digits == 8:
         print("What is your first number to add?")
         first_num = int(input("--> "))
         print("What is your second number to add?")
         second_num = int(input("--> "))
         print("What is your third number to add?")
         third_num = int(input("--> "))
         print("What is your fourth number to add?")
         fourth_num = int(input("--> "))
         print("What is your fifth number to add?")
         fifth_num = int(input("--> "))
         print("What is your sixth number to add?")
         sixth_num = int(input("--> "))
         print("What is your seventh number to add?")
         seventh_num = int(input("--> "))
         print("What is your eighth number to add?")
         eighth_num = int(input("--> "))
         ans = int(first_num + second_num + third_num + fourth_num + fifth_num + sixth_num + seventh_num + eighth_num)
         print("The result is ", ans, ".")
      elif num_digits == 9:
         print("What is your first number to add?")
         first_num = int(input("--> "))
         print("What is your second number to add?")
         second_num = int(input("--> "))
         print("What is your third number to add?")
         third_num = int(input("--> "))
         print("What is your fourth number to add?")
         fourth_num = int(input("--> "))
         print("What is your fifth number to add?")
         fifth_num = int(input("--> "))
         print("What is your sixth number to add?")
         sixth_num = int(input("--> "))
         print("What is your seventh number to add?")
         seventh_num = int(input("--> "))
         print("What is your eighth number to add?")
         eighth_num = int(input("--> "))
         print("What is your ninth number to add?")
         ninth_num = int(input("--> "))
         ans = int(first_num + second_num + third_num + fourth_num + fifth_num + sixth_num + seventh_num + eighth_num + ninth_num)
         print("The result is ", ans, ".")
      elif num_digits == 10:
         print("What is your first number to add?")
         first_num = int(input("--> "))
         print("What is your second number to add?")
         second_num = int(input("--> "))
         print("What is your third number to add?")
         third_num = int(input("--> "))
         print("What is your fourth number to add?")
         fourth_num = int(input("--> "))
         print("What is your fifth number to add?")
         fifth_num = int(input("--> "))
         print("What is your sixth number to add?")
         sixth_num = int(input("--> "))
         print("What is your seventh number to add?")
         seventh_num = int(input("--> "))
         print("What is your eighth number to add?")
         eighth_num = int(input("--> "))
         print("What is your ninth number to add?")
         ninth_num = int(input("--> "))
         print("What is your tenth number to add?")
         tenth_num = int(input("--> "))
         ans = int(first_num + second_num + third_num + fourth_num + fifth_num + sixth_num + seventh_num + eighth_num + ninth_num + tenth_num)
         print("The result is ", ans, ".")
      else:
         print("Please check your syntax. Rerun program and try again.")
elif operation == "subtract":
   print("What is your first number to subtract from?")
   first_num = input("--> ")
elif operation == "multiply":
   print("What is your first number to multiply?")
   first_num = input("--> ")
elif operation == "divide":
   print("What is your first number to divide from?")
   first_num = input("--> ")
elif operation == "quit":
   print("Thank you for using the Python Calculator. If you ever need me again, just rerun this program. Bye for now.")
else:
   print("Please check your syntax. Rerun program and try again.")
print("Thank you for using the Python Calculator. If you ever need me again, just rerun this program. Bye for now.")
